### ISSUE TITLE
Unable to display public forms (Cannot find module)

### ISSUE THREAD

**Issue by dokime7** [ohmyform/ohmyform#119]
## What's this issue about?
Unable to show forms to fill it

#### Expected behavior
Show the form

#### Actual behavior
The form page display: "An unexpected error has occurred."

#### UI container logs
```
ui_1     | Error: Cannot find module './images/index'
ui_1     | Require stack:
ui_1     | - /usr/src/app/node_modules/swiper/cjs/components/core/core-class.js
ui_1     | - /usr/src/app/node_modules/swiper/swiper.cjs.js
ui_1     | - /usr/src/app/node_modules/react-id-swiper/lib/ReactIdSwiper.js
ui_1     | - /usr/src/app/node_modules/react-id-swiper/lib/index.js
ui_1     | - /usr/src/app/.next/server/pages/form/[id].js
ui_1     | - /usr/src/app/node_modules/next/dist/next-server/server/require.js
ui_1     | - /usr/src/app/node_modules/next/dist/next-server/server/load-components.js
ui_1     | - /usr/src/app/node_modules/next/dist/next-server/server/api-utils.js
ui_1     | - /usr/src/app/node_modules/next/dist/next-server/server/next-server.js
ui_1     | - /usr/src/app/node_modules/next/dist/server/next.js
ui_1     | - /usr/src/app/node_modules/next/dist/server/lib/start-server.js
ui_1     | - /usr/src/app/node_modules/next/dist/cli/next-start.js
ui_1     | - /usr/src/app/node_modules/next/dist/bin/next
ui_1     |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ui_1     |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ui_1     |     at Module.require (internal/modules/cjs/loader.js:952:19)
ui_1     |     at require (internal/modules/cjs/helpers.js:88:18)
ui_1     |     at Object.<anonymous> (/usr/src/app/node_modules/swiper/cjs/components/core/core-class.js:44:39)
ui_1     |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ui_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ui_1     |     at Module.load (internal/modules/cjs/loader.js:928:32)
ui_1     |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ui_1     |     at Module.require (internal/modules/cjs/loader.js:952:19) {
ui_1     |   code: 'MODULE_NOT_FOUND',
ui_1     |   requireStack: [
ui_1     |     '/usr/src/app/node_modules/swiper/cjs/components/core/core-class.js',
ui_1     |     '/usr/src/app/node_modules/swiper/swiper.cjs.js',
ui_1     |     '/usr/src/app/node_modules/react-id-swiper/lib/ReactIdSwiper.js',
ui_1     |     '/usr/src/app/node_modules/react-id-swiper/lib/index.js',
ui_1     |     '/usr/src/app/.next/server/pages/form/[id].js',
ui_1     |     '/usr/src/app/node_modules/next/dist/next-server/server/require.js',
ui_1     |     '/usr/src/app/node_modules/next/dist/next-server/server/load-components.js',
ui_1     |     '/usr/src/app/node_modules/next/dist/next-server/server/api-utils.js',
ui_1     |     '/usr/src/app/node_modules/next/dist/next-server/server/next-server.js',
ui_1     |     '/usr/src/app/node_modules/next/dist/server/next.js',
ui_1     |     '/usr/src/app/node_modules/next/dist/server/lib/start-server.js',
ui_1     |     '/usr/src/app/node_modules/next/dist/cli/next-start.js',
ui_1     |     '/usr/src/app/node_modules/next/dist/bin/next'
ui_1     |   ]
ui_1     | }
```

#### Steps to reproduce
Create a form and clic on last button to show it.

#### Environment
Docker 19.03.11
Using: https://github.com/ohmyform/ohmyform/blob/master/examples/docker_for_load_balancing/docker-compose.yml
Image: ohmyform/ui:latest

**Comment by lucacalcaterra** [comment]
Same issue for me.

**Comment by mskymoore** [comment]
Same issue here

`version: "3"
networks:
    default:
        external:
            name: haproxy_webfrontend
    db:
    redis:
volumes:
    ohmyform_db:
services:
  redis:
    image: redis
    networks:
      redis:
  mongo:
    image: mongo
    networks:
      db:
    volumes:
      - "ohmyform_db:/data/db"
  ui:
    image: ohmyform/ui:latest
    networks:
      default:
    environment:
      API_HOST: https://frmapi.rwx.dev/graphql
      PORT: 5000
  api:
    image: ohmyform/api:latest
    networks:
      default:
      db:
      redis:
    environment:
      SIGNUP_DISABLED: "true"       
      NODE_ENV: "secure"
      CREATE_ADMIN: "true"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "admin"
      MONGODB_URI: mongodb://mongo/ohmyform
      MAILER_URI: smtp://mail.google.com
      REDIS_URL: redis://redis
      PORT: 5000
    depends_on:
      - mongo
      - redis`

**Comment by filipsheva** [comment]
Seems like a problem of underlying package - swiper.

Related ticket: https://github.com/nolimits4web/swiper/issues/3971

**Comment by wodka** [comment]
has been fixed a while ago - sry for missing this.

to stick with your current mongodb use 0.9 version
