### ISSUE TITLE
Minimal deployment not running - nest path error

### ISSUE THREAD

**Issue by MrFloppy** [ohmyform/ohmyform#149]
#### What's this issue about?
I tried to launch the minimal docker compose, but an error is preventing the complete boot up.

#### Expected behavior
Minimal docker compose should boot up an instance behind my traefik v2.

#### Actual behavior
Logs show the following error:
`
    cross-env NODE_ENV=production node dist/main
    
    2022-01-11 10:16:45,853 INFO success: api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    
    [Nest] 520  - 01/11/2022, 10:16:50 AM     LOG [NestFactory] Starting Nest application...
    
    [Nest] 520  - 01/11/2022, 10:16:50 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +33ms
    
    [Nest] 520  - 01/11/2022, 10:16:50 AM     LOG [InstanceLoader] MailerModule dependencies initialized +1ms
    
    [Nest] 520  - 01/11/2022, 10:16:50 AM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
    
    [Nest] 520  - 01/11/2022, 10:16:50 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
    
    [Nest] 520  - 01/11/2022, 10:16:50 AM   ERROR [ExceptionHandler] The "path" argument must be of type string. Received undefined

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

    at new NodeError (internal/errors.js:322:7)

    at validateString (internal/validators.js:124:11)

    at isAbsolute (path.js:1133:5)

    at fixTarget (/usr/src/api/node_modules/pino/lib/transport.js:116:9)

    at transport (/usr/src/api/node_modules/pino/lib/transport.js:111:22)

    at normalizeArgs (/usr/src/api/node_modules/pino/lib/tools.js:409:16)

    at pino (/usr/src/api/node_modules/pino/pino.js:84:28)

    at new PinoLogger (/usr/src/api/node_modules/nestjs-pino/PinoLogger.js:45:51)

    at Injector.instantiateClass (/usr/src/api/node_modules/@nestjs/core/injector/injector.js:301:19)

    at callback (/usr/src/api/node_modules/@nestjs/core/injector/injector.js:48:41)

    error Command failed with exit code 1.
    
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

#### Steps to reproduce
Use the minimal docker compose with traefik labels in my case.

#### Environment
Current docker and compose, including latest traefik.

`
version: "3"
services:
  ohmyform:
    image: ohmyform/ohmyform
    volumes:
      - "./data:/data"
    environment:
      CREATE_ADMIN: "TRUE"
      ADMIN_EMAIL: admin@localhost
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      DATABASE_DRIVER: sqlite
      DATABASE_URL: "sqlite:///data/data.sqlite"
      MAILER_URI: smtp://local.host
      LOGIN_NOTE: "Either login with admin:admin or create your own account to test OhMyForm"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.ohmyform.entrypoints=http"
      - "traefik.http.routers.ohmyform.rule=Host(`xxx`)"
      - "traefik.http.routers.ohmyform.middlewares=https-redirect@file"
      - "traefik.http.routers.ohmyform-secure.entrypoints=https"
      - "traefik.http.routers.ohmyform-secure.rule=Host(`xxx`)"
      - "traefik.http.routers.ohmyform-secure.tls=true"
      - "traefik.http.routers.ohmyform-secure.tls.certresolver=http"
      - "traefik.http.routers.ohmyform-secure.service=ohmyform"
      - "traefik.http.routers.ohmyform-secure.middlewares=secHeaders@file"
      - "traefik.http.services.ohmyform.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
networks:
  proxy:
    external:
      name: proxy
`

**Comment by fiqrimasngot** [comment]
also got same result
`
2022-01-11 20:54:49 | 2022-01-11 12:54:49,290 INFO success: api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-11 20:54:51 | [Nest] 648  - 01/11/2022, 12:54:51 PM     LOG [NestFactory] Starting Nest application...
2022-01-11 20:54:51 | [Nest] 648  - 01/11/2022, 12:54:51 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +28ms
2022-01-11 20:54:51 | [Nest] 648  - 01/11/2022, 12:54:51 PM     LOG [InstanceLoader] MailerModule dependencies initialized +1ms
2022-01-11 20:54:51 | [Nest] 648  - 01/11/2022, 12:54:51 PM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
2022-01-11 20:54:51 | [Nest] 648  - 01/11/2022, 12:54:51 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
2022-01-11 20:54:51 | [Nest] 648  - 01/11/2022, 12:54:51 PM   ERROR [ExceptionHandler] The "path" argument must be of type string. Received undefined
2022-01-11 20:54:51 | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
2022-01-11 20:54:51 | at new NodeError (internal/errors.js:322:7)
2022-01-11 20:54:51 | at validateString (internal/validators.js:124:11)
2022-01-11 20:54:51 | at isAbsolute (path.js:1133:5)
2022-01-11 20:54:51 | at fixTarget (/usr/src/api/node_modules/pino/lib/transport.js:116:9)
2022-01-11 20:54:51 | at transport (/usr/src/api/node_modules/pino/lib/transport.js:111:22)
2022-01-11 20:54:51 | at normalizeArgs (/usr/src/api/node_modules/pino/lib/tools.js:409:16)
2022-01-11 20:54:51 | at pino (/usr/src/api/node_modules/pino/pino.js:84:28)
2022-01-11 20:54:51 | at new PinoLogger (/usr/src/api/node_modules/nestjs-pino/PinoLogger.js:45:51)
2022-01-11 20:54:51 | at Injector.instantiateClass (/usr/src/api/node_modules/@nestjs/core/injector/injector.js:301:19)
2022-01-11 20:54:51 | at callback (/usr/src/api/node_modules/@nestjs/core/injector/injector.js:48:41)
2022-01-11 20:54:51 | error Command failed with exit code 1.


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
`

Following both minimal docker-compose and [this guide](https://ohmyform.com/docs/install/), the problem still persists.

**Comment by wodka** [comment]
thanks for reporting will check this soon

**Comment by wodka** [comment]
Problem is because of a configuration error (as described in https://github.com/iamolegga/nestjs-pino/pull/685)

-> container is currently building and should then include a fix for this! https://github.com/ohmyform/ohmyform/commit/3ad5c4e86b63bb3b9b3ad725fc0bbbaa9eb2b1d8

**Comment by wodka** [comment]
with a pull on the latest image it is now working again
