### ISSUE TITLE
Heroku deploy worked, but the web shows only "OhMyForm API endpoint"

### ISSUE THREAD

**Issue by dinoue** [ohmyform/ohmyform#154]
#### What's this issue about?

OMF, deployed to Heroku with 1-click button, does not show the screen like I expected.

#### Actual behavior

Like this.
![image](https://user-images.githubusercontent.com/1407574/153432658-7167d22a-877d-44b9-9648-63af7f54ee63.png)

**Comment by wodka** [comment]
:/ just confirmed the error

```
Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /tmp/build_6368a64b/ui/node_modules/next/dist/export/index.js:256:23
    at async Span.traceAsyncFn (/tmp/build_6368a64b/ui/node_modules/next/dist/trace/trace.js:74:20)
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This will need to work around the image loader in nextjs

**Comment by wodka** [comment]
installing now will fix the problem
