### ISSUE TITLE
Docker compose fail

### ISSUE THREAD

**Issue by BanyaiJozsef** [ohmyform/ohmyform#199]
Hi!

Ohmyform install is failed in docker. What is the problem and the solve? 

"failed to solve: executor failed running [/bin/sh -c touch /usr/src/api/src/schema.gql && chown 9999:9999 /usr/src/api/src/schema.gql]: exit code: 1"

Thx

**Comment by toabi** [comment]
docker compose also fails for me:


```
 > [api  7/10] RUN yarn install --frozen-lockfile:                                                                        
#0 0.386 yarn install v1.22.19                                                                                            
#0 0.462 [1/4] Resolving packages...                                                                                      
#0 0.722 [2/4] Fetching packages...                                                                                       
#0 34.52 [3/4] Linking dependencies...                                                                                    
#0 34.53 warning " > @nestjs-modules/mailer@1.6.1" has unmet peer dependency "@types/ejs@^3.0.3".                         
#0 34.53 warning " > @nestjs-modules/mailer@1.6.1" has unmet peer dependency "@types/pug@2.0.5".                          
#0 34.53 warning " > @nestjs-modules/mailer@1.6.1" has unmet peer dependency "ejs@^3.1.2".                                
#0 34.53 warning " > @nestjs-modules/mailer@1.6.1" has unmet peer dependency "pug@^2.0.4".                                
#0 34.53 warning " > apollo-server-express@3.6.3" has unmet peer dependency "express@^4.17.1".                            
#0 34.53 warning " > ts-loader@9.2.6" has unmet peer dependency "webpack@^5.0.0".                                         
#0 45.33 [4/4] Building fresh packages...
#0 46.27 error /usr/src/api/node_modules/bcrypt: Command failed.
#0 46.27 Exit code: 1
#0 46.27 Command: node-pre-gyp install --fallback-to-build
#0 46.27 Arguments: 
#0 46.27 Directory: /usr/src/api/node_modules/bcrypt
#0 46.27 Output:
#0 46.27 node-pre-gyp info it worked if it ends with ok
#0 46.27 node-pre-gyp info using node-pre-gyp@1.0.8
#0 46.27 node-pre-gyp info using node@16.17.1 | linux | arm64
#0 46.27 node-pre-gyp info check checked for "/usr/src/api/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
#0 46.27 node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-musl.tar.gz
#0 46.27 node-pre-gyp ERR! install response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-musl.tar.gz 
#0 46.27 node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@16.17.1 (node-v93 ABI, musl) (falling back to source compile with node-gyp) 
#0 46.27 node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-musl.tar.gz 
#0 46.27 gyp info it worked if it ends with ok
#0 46.27 gyp info using node-gyp@9.0.0
#0 46.27 gyp info using node@16.17.1 | linux | arm64
#0 46.27 gyp info ok 
#0 46.27 gyp info it worked if it ends with ok
#0 46.27 gyp info using node-gyp@9.0.0
#0 46.27 gyp info using node@16.17.1 | linux | arm64
#0 46.27 gyp ERR! find Python 
#0 46.27 gyp ERR! find Python Python is not set from command line or npm configuration
#0 46.27 gyp ERR! find Python Python is not set from environment variable PYTHON
#0 46.27 gyp ERR! find Python checking if "python3" can be used
#0 46.27 gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 46.27 gyp ERR! find Python checking if "python" can be used
#0 46.27 gyp ERR! find Python - "python" is not in PATH or produced an error
#0 46.27 gyp ERR! find Python 
#0 46.27 gyp ERR! find Python **********************************************************
#0 46.27 gyp ERR! find Python You need to install the latest version of Python.
#0 46.27 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 46.27 gyp ERR! find Python you can try one of the following options:
#0 46.27 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 46.27 gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 46.27 gyp ERR! find Python - Set the environment variable PYTHON
#0 46.27 gyp ERR! find Python - Set the npm configuration variable python:
#0 46.27 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 46.27 gyp ERR! find Python For more information consult the documentation at:
#0 46.27 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 46.27 gyp ERR! find Python **********************************************************
#0 46.27 gyp ERR! find Python 
#0 46.27 gyp ERR! configure error 
#0 46.27 gyp ERR! stack Error: Could not find any Python installation to use
#0 46.27 gyp ERR! stack     at PythonFinder.fail (/usr/src/api/node_modules/node-gyp/lib/find-python.js:330:47)
#0 46.27 gyp ERR! stack     at PythonFinder.runChecks (/usr/src/api/node_modules/node-gyp/lib/find-python.js:159:21)
#0 46.27 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/src/api/node_modules/node-gyp/lib/find-python.js:202:16)
#0 46.27 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/src/api/node_modules/node-gyp/lib/find-python.js:294:16)
#0 46.27 gyp ERR! stack     at exithandler (node:child_process:408:5)
#0 46.27 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
#0 46.27 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#0 46.27 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#0 46.27 gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#0 46.27 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#0 46.27 gyp ERR! System Linux 5.10.124-linuxkit
#0 46.27 gyp ERR! command "/usr/local/bin/node" "/usr/src/api/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/api/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/src/api/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
#0 46.27 gyp ERR! cwd /usr/src/api/node_modules/bcrypt
#0 46.27 gyp ERR! node -v v16.17.1
#0 46.27 gyp ERR! node-gyp -v v9.0.0
#0 46.27 gyp ERR! not ok 
#0 46.27 node-pre-gyp ERR! build error 
#0 46.27 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/src/api/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/api/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/src/api/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#0 46.27 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/api/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#0 46.27 node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#0 46.27 node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
#0 46.27 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
#0 46.27 node-pre-gyp ERR! System Linux 5.10.124-linuxkit
#0 46.27 node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/api/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#0 46.27 node-pre-gyp ERR! cwd /usr/src/api/node_modules/bcrypt
#0 46.27 node-pre-gyp ERR! node -v v16.17.1
#0 46.27 node-pre-gyp ERR! node-pre-gyp -v v1.0.8
#0 46.27 node-pre-gyp ERR! not ok 
#0 46.27 Failed to execute '/usr/local/bin/node /usr/src/api/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/api/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/src/api/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#0 46.27 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn install --frozen-lockfile]: exit code: 1
```

Building on macOS arm64 may be a reason?

**Comment by BanyaiJozsef** [comment]
No, Win 10. Virtualization is also on. I don't know what the problem could
be...

Tobias Birmili ***@***.***> ezt írta (időpont: 2022. okt.
11., K, 8:28):

**Comment by wodka** [comment]
:/ will check this soon. in the meantime you could use the prebuilt images at dockerhub instead of building from source

**Comment by dima1206** [comment]
Not sure about the second comment, but I had the same error as OP, solved with `git submodule update --init`. 

(Still couldn't finish it due to CPU and RAM limitations)

**Comment by xwenc** [comment]
![image](https://github.com/ohmyform/ohmyform/assets/14305804/a78f4a2b-ff73-482e-b708-aadcc4dd2f01)
If you use an m2 chip mac like me, please add platform: "linux/amd64" to the docker-compose.yml file, It works for me
