### ISSUE TITLE
Demo server died after type error.

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#8]
```BASH

root@GoldenGod:~/ohmyform# docker-compose ps
         Name                        Command               State                 Ports
----------------------------------------------------------------------------------------------------
ohmyform_mail_1           MailHog                          Up       1025/tcp, 0.0.0.0:5050->8025/tcp
ohmyform_mongo_1          docker-entrypoint.sh mongod      Up       27017/tcp
ohmyform_mongoexpress_1   tini -- /docker-entrypoint ...   Up       0.0.0.0:5051->8081/tcp
ohmyform_redis_1          docker-entrypoint.sh redis ...   Up       6379/tcp
ohmyform_tellform_1       docker-entrypoint.sh node  ...   Exit 1
root@GoldenGod:~/ohmyform# docker-compose logs -f --tail=100 tellform
Attaching to ohmyform_tellform_1
tellform_1      | {"message":"\u001b[0mGET /static/lib/angular-ui-date/src/date.js \u001b[32m200 \u001b[0m0.485 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/lib/tableExport.jquery.plugin/tableExport.min.js \u001b[32m200 \u001b[0m0.493 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/lib/ngclipboard/dist/ngclipboard.min.js \u001b[32m200 \u001b[0m0.431 ms - 681\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/lib/bootstrap-switch/dist/js/bootstrap-switch.min.js \u001b[32m200 \u001b[0m0.343 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/lib/angular-bootstrap-switch/dist/angular-bootstrap-switch.min.js \u001b[32m200 \u001b[0m0.422 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/lib/ng-quill/src/ng-quill.js \u001b[32m200 \u001b[0m0.371 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/config.js \u001b[32m200 \u001b[0m0.573 ms - 750\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/application.js \u001b[32m200 \u001b[0m0.276 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/dist/populate_template_cache.js \u001b[32m200 \u001b[0m0.364 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/dist/form_populate_template_cache.js \u001b[32m200 \u001b[0m0.497 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/core.client.module.js \u001b[32m200 \u001b[0m0.355 ms - 140\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/forms.client.module.js \u001b[32m200 \u001b[0m0.376 ms - 322\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/users.client.module.js \u001b[32m200 \u001b[0m0.340 ms - 129\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/config/core.client.routes.js \u001b[32m200 \u001b[0m0.450 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/controllers/header.client.controller.js \u001b[32m200 \u001b[0m0.313 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/services/menus.client.service.js \u001b[32m200 \u001b[0m0.494 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/services/subdomain.client.service.js \u001b[32m200 \u001b[0m0.620 ms - 207\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/config/forms.client.config.js \u001b[32m200 \u001b[0m0.522 ms - 961\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/config/forms.client.routes.js \u001b[32m200 \u001b[0m0.419 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/users.client.config.js \u001b[32m200 \u001b[0m0.289 ms - 801\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/services/forms.client.service.js \u001b[32m200 \u001b[0m0.257 ms - 733\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/users.client.routes.js \u001b[32m200 \u001b[0m0.394 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/controllers/authentication.client.controller.js \u001b[32m200 \u001b[0m0.384 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/controllers/change_password.client.controller.js \u001b[32m200 \u001b[0m0.428 ms - 790\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/controllers/settings.client.controller.js \u001b[32m200 \u001b[0m0.418 ms - 784\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/controllers/password.client.controller.js \u001b[32m200 \u001b[0m0.507 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/controllers/verify.client.controller.js \u001b[32m200 \u001b[0m0.437 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/services/auth.client.service.js \u001b[32m200 \u001b[0m0.436 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/services/authorizer.client.service.js \u001b[32m200 \u001b[0m0.270 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/services/user.client.service.js \u001b[32m200 \u001b[0m0.338 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/services/users.client.service.js \u001b[32m200 \u001b[0m0.498 ms - 270\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/config/i18n/english.js \u001b[32m200 \u001b[0m0.371 ms - 496\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/config/i18n/french.js \u001b[32m200 \u001b[0m0.278 ms - 426\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/config/i18n/german.js \u001b[32m200 \u001b[0m0.291 ms - 408\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/config/i18n/italian.js \u001b[32m200 \u001b[0m0.369 ms - 401\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/config/i18n/spanish.js \u001b[32m200 \u001b[0m0.484 ms - 405\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/config/i18n/swedish.js \u001b[32m200 \u001b[0m0.389 ms - 406\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/controllers/list-forms.client.controller.js \u001b[32m200 \u001b[0m0.473 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/controllers/admin-form.client.controller.js \u001b[32m200 \u001b[0m0.385 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/directives/edit-submissions-form.client.directive.js \u001b[32m200 \u001b[0m0.508 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/directives/edit-form.client.directive.js \u001b[32m200 \u001b[0m0.632 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/directives/configure-form.client.directive.js \u001b[32m200 \u001b[0m0.356 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/directives/design-form.client.directive.js \u001b[32m200 \u001b[0m0.336 ms - 348\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/directives/field-icon.client.directive.js \u001b[32m200 \u001b[0m0.465 ms - 873\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/directives/share-form.client.directive.js \u001b[32m200 \u001b[0m0.350 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/services/submissions.client.service.js \u001b[32m200 \u001b[0m0.425 ms - 437\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/services/form-fields.client.service.js \u001b[32m200 \u001b[0m0.258 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/i18n/english.js \u001b[32m200 \u001b[0m0.477 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/i18n/french.js \u001b[32m200 \u001b[0m0.354 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/i18n/german.js \u001b[32m200 \u001b[0m0.525 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/i18n/italian.js \u001b[32m200 \u001b[0m0.462 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/i18n/spanish.js \u001b[32m200 \u001b[0m0.426 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/users/config/i18n/swedish.js \u001b[32m200 \u001b[0m0.951 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/config/i18n/english.js \u001b[32m200 \u001b[0m0.362 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/config/i18n/french.js \u001b[32m200 \u001b[0m0.336 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/config/i18n/german.js \u001b[32m200 \u001b[0m0.331 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/config/i18n/italian.js \u001b[32m200 \u001b[0m0.320 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/config/i18n/spanish.js \u001b[32m200 \u001b[0m0.419 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/forms.client.module.js \u001b[32m200 \u001b[0m0.422 ms - 185\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/forms/admin/config/i18n/swedish.js \u001b[32m200 \u001b[0m0.352 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/directives/analytics-service.client.directive.js \u001b[32m200 \u001b[0m0.326 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/directives/key-to-option.client.directive.js \u001b[32m200 \u001b[0m0.270 ms - 810\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/directives/key-to-truthy.client.directive.js \u001b[32m200 \u001b[0m0.316 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/config/forms.client.config.js \u001b[32m200 \u001b[0m0.732 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/config/i18n/english.js \u001b[32m200 \u001b[0m0.587 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/config/i18n/french.js \u001b[32m200 \u001b[0m0.401 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/config/i18n/german.js \u001b[32m200 \u001b[0m0.377 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/config/i18n/italian.js \u001b[32m200 \u001b[0m0.352 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/config/i18n/spanish.js \u001b[32m200 \u001b[0m0.332 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/config/i18n/swedish.js \u001b[32m200 \u001b[0m0.447 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/controllers/submit-form.client.controller.js \u001b[32m200 \u001b[0m0.362 ms - 404\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/directives/field.client.directive.js \u001b[32m200 \u001b[0m0.428 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/directives/on-enter-key.client.directive.js \u001b[32m200 \u001b[0m0.451 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/directives/on-finish-render.client.directive.js \u001b[32m200 \u001b[0m0.475 ms - 859\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/services/current-form.client.service.js \u001b[32m200 \u001b[0m0.324 ms - 346\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/directives/submit-form.client.directive.js \u001b[32m200 \u001b[0m0.421 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/services/forms.client.service.js \u001b[32m200 \u001b[0m0.352 ms - 672\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/services/time-counter.client.service.js \u001b[32m200 \u001b[0m0.274 ms - 755\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/form_modules/forms/base/services/socket.io.client.service.js \u001b[32m200 \u001b[0m0.407 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/img/logo_white.svg \u001b[32m200 \u001b[0m0.542 ms - 9508\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET /static/modules/core/img/brand/favicon.ico \u001b[32m200 \u001b[0m0.527 ms - 15086\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mPOST /auth/signin \u001b[33m400 \u001b[0m3.025 ms - 46\u001b[0m\n","level":"info"}
tellform_1      | {"message":"\u001b[0mGET / \u001b[32m200 \u001b[0m68.976 ms - -\u001b[0m\n","level":"info"}
tellform_1      | {"error":{},"level":"error","message":"uncaughtException: Callback must be a function\nTypeError [ERR_INVALID_CALLBACK]: Callback must be a function\n  at Object.randomBytes (internal/crypto/random.js:48:11)\n  at Object.options.source (/opt/app/node_modules/rand-token/index.js:60:25)\n  at Object.generate (/opt/app/node_modules/rand-token/index.js:95:29)\n  at /opt/app/node_modules/email-verification/index.js:301:68\n  at /opt/app/node_modules/mongoose/lib/model.js:4462:16\n  at /opt/app/node_modules/mongoose/lib/query.js:4283:12\n  at model.Query.Query._completeOne (/opt/app/node_modules/mongoose/lib/query.js:1995:12)\n  at Immediate.Query.base.findOne.call (/opt/app/node_modules/mongoose/lib/query.js:2057:10)\n  at Immediate.<anonymous> (/opt/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:116:16)\n  at runCallback (timers.js:705:18)\n  at tryOnImmediate (timers.js:676:5)\n  at processImmediate (timers.js:658:5)\n  at process.topLevelDomainCallback (domain.js:126:23)\n","stack":"TypeError [ERR_INVALID_CALLBACK]: Callback must be a function\n  at Object.randomBytes (internal/crypto/random.js:48:11)\n  at Object.options.source (/opt/app/node_modules/rand-token/index.js:60:25)\n  at Object.generate (/opt/app/node_modules/rand-token/index.js:95:29)\n  at /opt/app/node_modules/email-verification/index.js:301:68\n  at /opt/app/node_modules/mongoose/lib/model.js:4462:16\n  at /opt/app/node_modules/mongoose/lib/query.js:4283:12\n  at model.Query.Query._completeOne (/opt/app/node_modules/mongoose/lib/query.js:1995:12)\n  at Immediate.Query.base.findOne.call (/opt/app/node_modules/mongoose/lib/query.js:2057:10)\n  at Immediate.<anonymous> (/opt/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:116:16)\n  at runCallback (timers.js:705:18)\n  at tryOnImmediate (timers.js:676:5)\n  at processImmediate (timers.js:658:5)\n  at process.topLevelDomainCallback (domain.js:126:23)\n","exception":true,"date":"Thu Jul 18 2019 00:18:42 GMT+0000 (Coordinated Universal Time)","process":{"pid":1,"uid":0,"gid":0,"cwd":"/opt/app","execPath":"/usr/local/bin/node","version":"v10.16.0","argv":["/usr/local/bin/node","/opt/app/server.js"],"memoryUsage":{"rss":138514432,"heapTotal":76132352,"heapUsed":65752632,"external":38177190}},"os":{"loadavg":[0,0.00732421875,0],"uptime":16108},"trace":[{"column":11,"file":"internal/crypto/random.js","function":"Object.randomBytes","line":48,"method":"randomBytes","native":false},{"column":25,"file":"/opt/app/node_modules/rand-token/index.js","function":"Object.options.source","line":60,"method":"options.source","native":false},{"column":29,"file":"/opt/app/node_modules/rand-token/index.js","function":"Object.generate","line":95,"method":"generate","native":false},{"column":68,"file":"/opt/app/node_modules/email-verification/index.js","function":null,"line":301,"method":null,"native":false},{"column":16,"file":"/opt/app/node_modules/mongoose/lib/model.js","function":null,"line":4462,"method":null,"native":false},{"column":12,"file":"/opt/app/node_modules/mongoose/lib/query.js","function":null,"line":4283,"method":null,"native":false},{"column":12,"file":"/opt/app/node_modules/mongoose/lib/query.js","function":"model.Query.Query._completeOne","line":1995,"method":"Query.Query._completeOne","native":false},{"column":10,"file":"/opt/app/node_modules/mongoose/lib/query.js","function":"Immediate.Query.base.findOne.call","line":2057,"method":"Query.base.findOne.call","native":false},{"column":16,"file":"/opt/app/node_modules/mongoose/node_modules/mquery/lib/utils.js","function":"","line":116,"method":null,"native":false},{"column":18,"file":"timers.js","function":"runCallback","line":705,"method":null,"native":false},{"column":5,"file":"timers.js","function":"tryOnImmediate","line":676,"method":null,"native":false},{"column":5,"file":"timers.js","function":"processImmediate","line":658,"method":null,"native":false},{"column":23,"file":"domain.js","function":"process.topLevelDomainCallback","line":126,"method":"topLevelDomainCallback","native":false}]}
tellform_1      | Thu, 18 Jul 2019 00:18:42 GMT uncaughtException: Callback must be a function
tellform_1      | TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
tellform_1      |   at Object.randomBytes (internal/crypto/random.js:48:11)
tellform_1      |   at Object.options.source (/opt/app/node_modules/rand-token/index.js:60:25)
tellform_1      |   at Object.generate (/opt/app/node_modules/rand-token/index.js:95:29)
tellform_1      |   at /opt/app/node_modules/email-verification/index.js:301:68
tellform_1      |   at /opt/app/node_modules/mongoose/lib/model.js:4462:16
tellform_1      |   at /opt/app/node_modules/mongoose/lib/query.js:4283:12
tellform_1      |   at model.Query.Query._completeOne (/opt/app/node_modules/mongoose/lib/query.js:1995:12)
tellform_1      |   at Immediate.Query.base.findOne.call (/opt/app/node_modules/mongoose/lib/query.js:2057:10)
tellform_1      |   at Immediate.<anonymous> (/opt/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:116:16)
tellform_1      |   at runCallback (timers.js:705:18)
tellform_1      |   at tryOnImmediate (timers.js:676:5)
tellform_1      |   at processImmediate (timers.js:658:5)
tellform_1      |   at process.topLevelDomainCallback (domain.js:126:23)
tellform_1      |
ohmyform_tellform_1 exited with code 1```

**Comment by wodka** [comment]
:/ reason is the old rand-token package used in https://github.com/whitef0x0/node-email-verification which is not working with NodeJS >= 9
